insert into nationality (id,nationality_code) values (nationality_id.nextval,'ad');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ae');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'af');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ai');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'al');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'am');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ao');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'aq');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ar');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'as');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'at');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'au');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'aw');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ba');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bb');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'be');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bf');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bg');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bh');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bj');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bm');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bo');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'br');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bs');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bt');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bw');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'by');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'bz');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ca');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cg');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ch');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ci');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cl');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cm');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cn');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'co');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cr');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cu');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cy');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'cz');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'de');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'dk');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'dm');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'dz');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ec');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ee');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'eg');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'el');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'es');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'et');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'fi');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'fj');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'fr');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ga');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'gb');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ge');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'gh');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'gn');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'gy');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'hk');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'hr');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ht');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'hu');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'id');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ie');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'il');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'in');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'iq');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ir');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'is');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'it');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'jm');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'jo');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'jp');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ke');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'kh');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'kr');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'kw');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'kz');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'lb');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'lk');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'lt');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'lu');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'lv');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ma');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mc');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'me');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mg');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mk');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ml');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mm');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mn');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mo');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mt');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mu');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mv');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'mx');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'my');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'na');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ng');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'nl');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'no');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'np');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'nz');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'om');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'pa');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'pe');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ph');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'pk');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'pl');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ps');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'pt');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'py');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'qa');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ro');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ru');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'sa');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'sc');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'se');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'sg');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'si');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'sk');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'sn');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'so');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'th');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'tj');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'tn');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'tr');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'tw');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'tz');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ua');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ug');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'us');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'uy');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'uz');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ve');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'vn');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'ye');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'za');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'zm');
insert into nationality (id,nationality_code) values (nationality_id.nextval,'zw');
commit;

insert into country (id,country_code) values (country_id.nextval,'ad');
insert into country (id,country_code) values (country_id.nextval,'ae');
insert into country (id,country_code) values (country_id.nextval,'af');
insert into country (id,country_code) values (country_id.nextval,'ag');
insert into country (id,country_code) values (country_id.nextval,'ai');
insert into country (id,country_code) values (country_id.nextval,'al');
insert into country (id,country_code) values (country_id.nextval,'am');
insert into country (id,country_code) values (country_id.nextval,'ao');
insert into country (id,country_code) values (country_id.nextval,'aq');
insert into country (id,country_code) values (country_id.nextval,'ar');
insert into country (id,country_code) values (country_id.nextval,'as');
insert into country (id,country_code) values (country_id.nextval,'at');
insert into country (id,country_code) values (country_id.nextval,'au');
insert into country (id,country_code) values (country_id.nextval,'aw');
insert into country (id,country_code) values (country_id.nextval,'ax');
insert into country (id,country_code) values (country_id.nextval,'az');
insert into country (id,country_code) values (country_id.nextval,'ba');
insert into country (id,country_code) values (country_id.nextval,'bb');
insert into country (id,country_code) values (country_id.nextval,'bd');
insert into country (id,country_code) values (country_id.nextval,'be');
insert into country (id,country_code) values (country_id.nextval,'bf');
insert into country (id,country_code) values (country_id.nextval,'bg');
insert into country (id,country_code) values (country_id.nextval,'bh');
insert into country (id,country_code) values (country_id.nextval,'bi');
insert into country (id,country_code) values (country_id.nextval,'bj');
insert into country (id,country_code) values (country_id.nextval,'bl');
insert into country (id,country_code) values (country_id.nextval,'bm');
insert into country (id,country_code) values (country_id.nextval,'bn');
insert into country (id,country_code) values (country_id.nextval,'bo');
insert into country (id,country_code) values (country_id.nextval,'bq');
insert into country (id,country_code) values (country_id.nextval,'br');
insert into country (id,country_code) values (country_id.nextval,'bs');
insert into country (id,country_code) values (country_id.nextval,'bt');
insert into country (id,country_code) values (country_id.nextval,'bw');
insert into country (id,country_code) values (country_id.nextval,'by');
insert into country (id,country_code) values (country_id.nextval,'bz');
insert into country (id,country_code) values (country_id.nextval,'ca');
insert into country (id,country_code) values (country_id.nextval,'cc');
insert into country (id,country_code) values (country_id.nextval,'cd');
insert into country (id,country_code) values (country_id.nextval,'cf');
insert into country (id,country_code) values (country_id.nextval,'cg');
insert into country (id,country_code) values (country_id.nextval,'ch');
insert into country (id,country_code) values (country_id.nextval,'ci');
insert into country (id,country_code) values (country_id.nextval,'ck');
insert into country (id,country_code) values (country_id.nextval,'cl');
insert into country (id,country_code) values (country_id.nextval,'cm');
insert into country (id,country_code) values (country_id.nextval,'cn');
insert into country (id,country_code) values (country_id.nextval,'co');
insert into country (id,country_code) values (country_id.nextval,'cr');
insert into country (id,country_code) values (country_id.nextval,'cu');
insert into country (id,country_code) values (country_id.nextval,'cv');
insert into country (id,country_code) values (country_id.nextval,'cw');
insert into country (id,country_code) values (country_id.nextval,'cx');
insert into country (id,country_code) values (country_id.nextval,'cy');
insert into country (id,country_code) values (country_id.nextval,'cz');
insert into country (id,country_code) values (country_id.nextval,'de');
insert into country (id,country_code) values (country_id.nextval,'dj');
insert into country (id,country_code) values (country_id.nextval,'dk');
insert into country (id,country_code) values (country_id.nextval,'dm');
insert into country (id,country_code) values (country_id.nextval,'do');
insert into country (id,country_code) values (country_id.nextval,'dz');
insert into country (id,country_code) values (country_id.nextval,'ec');
insert into country (id,country_code) values (country_id.nextval,'ee');
insert into country (id,country_code) values (country_id.nextval,'eg');
insert into country (id,country_code) values (country_id.nextval,'eh');
insert into country (id,country_code) values (country_id.nextval,'el');
insert into country (id,country_code) values (country_id.nextval,'er');
insert into country (id,country_code) values (country_id.nextval,'es');
insert into country (id,country_code) values (country_id.nextval,'et');
insert into country (id,country_code) values (country_id.nextval,'fi');
insert into country (id,country_code) values (country_id.nextval,'fj');
insert into country (id,country_code) values (country_id.nextval,'fk');
insert into country (id,country_code) values (country_id.nextval,'fm');
insert into country (id,country_code) values (country_id.nextval,'fo');
insert into country (id,country_code) values (country_id.nextval,'fr');
insert into country (id,country_code) values (country_id.nextval,'ga');
insert into country (id,country_code) values (country_id.nextval,'gb');
insert into country (id,country_code) values (country_id.nextval,'gd');
insert into country (id,country_code) values (country_id.nextval,'ge');
insert into country (id,country_code) values (country_id.nextval,'gf');
insert into country (id,country_code) values (country_id.nextval,'gg');
insert into country (id,country_code) values (country_id.nextval,'gh');
insert into country (id,country_code) values (country_id.nextval,'gi');
insert into country (id,country_code) values (country_id.nextval,'gl');
insert into country (id,country_code) values (country_id.nextval,'gm');
insert into country (id,country_code) values (country_id.nextval,'gn');
insert into country (id,country_code) values (country_id.nextval,'gp');
insert into country (id,country_code) values (country_id.nextval,'gq');
insert into country (id,country_code) values (country_id.nextval,'gs');
insert into country (id,country_code) values (country_id.nextval,'gt');
insert into country (id,country_code) values (country_id.nextval,'gu');
insert into country (id,country_code) values (country_id.nextval,'gw');
insert into country (id,country_code) values (country_id.nextval,'gy');
insert into country (id,country_code) values (country_id.nextval,'hk');
insert into country (id,country_code) values (country_id.nextval,'hn');
insert into country (id,country_code) values (country_id.nextval,'hr');
insert into country (id,country_code) values (country_id.nextval,'ht');
insert into country (id,country_code) values (country_id.nextval,'hu');
insert into country (id,country_code) values (country_id.nextval,'ic');
insert into country (id,country_code) values (country_id.nextval,'id');
insert into country (id,country_code) values (country_id.nextval,'ie');
insert into country (id,country_code) values (country_id.nextval,'il');
insert into country (id,country_code) values (country_id.nextval,'im');
insert into country (id,country_code) values (country_id.nextval,'in');
insert into country (id,country_code) values (country_id.nextval,'io');
insert into country (id,country_code) values (country_id.nextval,'iq');
insert into country (id,country_code) values (country_id.nextval,'ir');
insert into country (id,country_code) values (country_id.nextval,'is');
insert into country (id,country_code) values (country_id.nextval,'it');
insert into country (id,country_code) values (country_id.nextval,'je');
insert into country (id,country_code) values (country_id.nextval,'jm');
insert into country (id,country_code) values (country_id.nextval,'jo');
insert into country (id,country_code) values (country_id.nextval,'jp');
insert into country (id,country_code) values (country_id.nextval,'ke');
insert into country (id,country_code) values (country_id.nextval,'kg');
insert into country (id,country_code) values (country_id.nextval,'kh');
insert into country (id,country_code) values (country_id.nextval,'ki');
insert into country (id,country_code) values (country_id.nextval,'km');
insert into country (id,country_code) values (country_id.nextval,'kn');
insert into country (id,country_code) values (country_id.nextval,'kp');
insert into country (id,country_code) values (country_id.nextval,'kr');
insert into country (id,country_code) values (country_id.nextval,'kw');
insert into country (id,country_code) values (country_id.nextval,'ky');
insert into country (id,country_code) values (country_id.nextval,'kz');
insert into country (id,country_code) values (country_id.nextval,'la');
insert into country (id,country_code) values (country_id.nextval,'lb');
insert into country (id,country_code) values (country_id.nextval,'lc');
insert into country (id,country_code) values (country_id.nextval,'li');
insert into country (id,country_code) values (country_id.nextval,'lk');
insert into country (id,country_code) values (country_id.nextval,'lr');
insert into country (id,country_code) values (country_id.nextval,'ls');
insert into country (id,country_code) values (country_id.nextval,'lt');
insert into country (id,country_code) values (country_id.nextval,'lu');
insert into country (id,country_code) values (country_id.nextval,'lv');
insert into country (id,country_code) values (country_id.nextval,'ly');
insert into country (id,country_code) values (country_id.nextval,'ma');
insert into country (id,country_code) values (country_id.nextval,'mc');
insert into country (id,country_code) values (country_id.nextval,'md');
insert into country (id,country_code) values (country_id.nextval,'me');
insert into country (id,country_code) values (country_id.nextval,'mf');
insert into country (id,country_code) values (country_id.nextval,'mg');
insert into country (id,country_code) values (country_id.nextval,'mh');
insert into country (id,country_code) values (country_id.nextval,'mk');
insert into country (id,country_code) values (country_id.nextval,'ml');
insert into country (id,country_code) values (country_id.nextval,'mm');
insert into country (id,country_code) values (country_id.nextval,'mn');
insert into country (id,country_code) values (country_id.nextval,'mo');
insert into country (id,country_code) values (country_id.nextval,'mp');
insert into country (id,country_code) values (country_id.nextval,'mq');
insert into country (id,country_code) values (country_id.nextval,'mr');
insert into country (id,country_code) values (country_id.nextval,'ms');
insert into country (id,country_code) values (country_id.nextval,'mt');
insert into country (id,country_code) values (country_id.nextval,'mu');
insert into country (id,country_code) values (country_id.nextval,'mv');
insert into country (id,country_code) values (country_id.nextval,'mw');
insert into country (id,country_code) values (country_id.nextval,'mx');
insert into country (id,country_code) values (country_id.nextval,'my');
insert into country (id,country_code) values (country_id.nextval,'mz');
insert into country (id,country_code) values (country_id.nextval,'na');
insert into country (id,country_code) values (country_id.nextval,'nc');
insert into country (id,country_code) values (country_id.nextval,'ne');
insert into country (id,country_code) values (country_id.nextval,'nf');
insert into country (id,country_code) values (country_id.nextval,'ng');
insert into country (id,country_code) values (country_id.nextval,'ni');
insert into country (id,country_code) values (country_id.nextval,'nl');
insert into country (id,country_code) values (country_id.nextval,'no');
insert into country (id,country_code) values (country_id.nextval,'np');
insert into country (id,country_code) values (country_id.nextval,'nr');
insert into country (id,country_code) values (country_id.nextval,'nu');
insert into country (id,country_code) values (country_id.nextval,'nz');
insert into country (id,country_code) values (country_id.nextval,'om');
insert into country (id,country_code) values (country_id.nextval,'pa');
insert into country (id,country_code) values (country_id.nextval,'pe');
insert into country (id,country_code) values (country_id.nextval,'pf');
insert into country (id,country_code) values (country_id.nextval,'pg');
insert into country (id,country_code) values (country_id.nextval,'ph');
insert into country (id,country_code) values (country_id.nextval,'pk');
insert into country (id,country_code) values (country_id.nextval,'pl');
insert into country (id,country_code) values (country_id.nextval,'pm');
insert into country (id,country_code) values (country_id.nextval,'pn');
insert into country (id,country_code) values (country_id.nextval,'pr');
insert into country (id,country_code) values (country_id.nextval,'ps');
insert into country (id,country_code) values (country_id.nextval,'pt');
insert into country (id,country_code) values (country_id.nextval,'pw');
insert into country (id,country_code) values (country_id.nextval,'py');
insert into country (id,country_code) values (country_id.nextval,'qa');
insert into country (id,country_code) values (country_id.nextval,'re');
insert into country (id,country_code) values (country_id.nextval,'ro');
insert into country (id,country_code) values (country_id.nextval,'rs');
insert into country (id,country_code) values (country_id.nextval,'ru');
insert into country (id,country_code) values (country_id.nextval,'rw');
insert into country (id,country_code) values (country_id.nextval,'sa');
insert into country (id,country_code) values (country_id.nextval,'sb');
insert into country (id,country_code) values (country_id.nextval,'sc');
insert into country (id,country_code) values (country_id.nextval,'sd');
insert into country (id,country_code) values (country_id.nextval,'se');
insert into country (id,country_code) values (country_id.nextval,'sg');
insert into country (id,country_code) values (country_id.nextval,'sh');
insert into country (id,country_code) values (country_id.nextval,'si');
insert into country (id,country_code) values (country_id.nextval,'sj');
insert into country (id,country_code) values (country_id.nextval,'sk');
insert into country (id,country_code) values (country_id.nextval,'sl');
insert into country (id,country_code) values (country_id.nextval,'sm');
insert into country (id,country_code) values (country_id.nextval,'sn');
insert into country (id,country_code) values (country_id.nextval,'so');
insert into country (id,country_code) values (country_id.nextval,'sr');
insert into country (id,country_code) values (country_id.nextval,'st');
insert into country (id,country_code) values (country_id.nextval,'sv');
insert into country (id,country_code) values (country_id.nextval,'sy');
insert into country (id,country_code) values (country_id.nextval,'sz');
insert into country (id,country_code) values (country_id.nextval,'tc');
insert into country (id,country_code) values (country_id.nextval,'td');
insert into country (id,country_code) values (country_id.nextval,'tf');
insert into country (id,country_code) values (country_id.nextval,'tg');
insert into country (id,country_code) values (country_id.nextval,'th');
insert into country (id,country_code) values (country_id.nextval,'tj');
insert into country (id,country_code) values (country_id.nextval,'tk');
insert into country (id,country_code) values (country_id.nextval,'tl');
insert into country (id,country_code) values (country_id.nextval,'tm');
insert into country (id,country_code) values (country_id.nextval,'tn');
insert into country (id,country_code) values (country_id.nextval,'to');
insert into country (id,country_code) values (country_id.nextval,'tr');
insert into country (id,country_code) values (country_id.nextval,'tt');
insert into country (id,country_code) values (country_id.nextval,'tv');
insert into country (id,country_code) values (country_id.nextval,'tw');
insert into country (id,country_code) values (country_id.nextval,'tz');
insert into country (id,country_code) values (country_id.nextval,'ua');
insert into country (id,country_code) values (country_id.nextval,'ug');
insert into country (id,country_code) values (country_id.nextval,'um');
insert into country (id,country_code) values (country_id.nextval,'us');
insert into country (id,country_code) values (country_id.nextval,'uy');
insert into country (id,country_code) values (country_id.nextval,'uz');
insert into country (id,country_code) values (country_id.nextval,'va');
insert into country (id,country_code) values (country_id.nextval,'vc');
insert into country (id,country_code) values (country_id.nextval,'ve');
insert into country (id,country_code) values (country_id.nextval,'vg');
insert into country (id,country_code) values (country_id.nextval,'vi');
insert into country (id,country_code) values (country_id.nextval,'vn');
insert into country (id,country_code) values (country_id.nextval,'vu');
insert into country (id,country_code) values (country_id.nextval,'wf');
insert into country (id,country_code) values (country_id.nextval,'ws');
insert into country (id,country_code) values (country_id.nextval,'ye');
insert into country (id,country_code) values (country_id.nextval,'yt');
insert into country (id,country_code) values (country_id.nextval,'za');
insert into country (id,country_code) values (country_id.nextval,'zm');
insert into country (id,country_code) values (country_id.nextval,'zw');
commit;

insert into language (id, two_chars_code, use_by_default) values (language_id.nextval, 'en', 0);
insert into language (id, two_chars_code, use_by_default) values (language_id.nextval, 'fr', 1);

insert into requestor_config(id,order_validation_page_ttl,short_flow) values (requestor_config_id.nextval, 86400000, 0);
insert into requestor (id,service_name,config_id) values (requestor_id.nextval,'DG Sante', requestor_config_id.currval);

insert into requestor_config(id,order_validation_page_ttl,short_flow) values (requestor_config_id.nextval, 86400000, 1);
insert into requestor (id,service_name, config_id) values (requestor_id.nextval,'BTA', requestor_config_id.currval);

insert into role (id,role_type) values (role_id.nextval,'FLOWERS_ADMIN');
insert into role (id,role_type) values (role_id.nextval,'END_USER');
insert into role (id,role_type) values (role_id.nextval,'CSD_AGENT');
insert into role (id,role_type) values (role_id.nextval,'DIA');
insert into role (id,role_type) values (role_id.nextval,'LUXTRUST_ADMIN');
insert into role (id,role_type) values (role_id.nextval,'GDPR_AGENT');
insert into role (id,role_type) values (role_id.nextval,'ESEAL_MANAGER');
insert into role (id,role_type) values (role_id.nextval,'ESEAL_OFFICER');

insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='at'),'ATU[0-9]{8}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='be'),'BE0[0-9]{9}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='bg'),'(BG[0-9]{9})|(BG[0-9]{10})');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='cy'),'CY[0-9]{8}[A-Z]{1}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='cz'),'(CZ[0-9]{8})|(CZ[0-9]{9})|(CZ[0-9]{10})');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='de'),'DE[0-9]{9}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='dk'),'DK[0-9]{8}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='ee'),'EE[0-9]{9}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='es'),'ES[0-9A-Z]{1}[0-9]{7}[0-9A-Z]{1}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='fi'),'FI[0-9]{8}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='fr'),'FR[0-9A-Z]{2}[0-9]{9}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='gb'),'^(GB([0-9]{9})|([0-9]{12}))|(GB(GD|HA)[0-9]{3})$');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='el'),'EL[0-9]{9}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='hu'),'HU[0-9]{8}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='ie'),'IE[0-9]{1}([0-9A-Z]|[\+]|[\*]){1}[0-9]{5}[A-Z]{1}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='im'),'^(GB([0-9]{9})|([0-9]{12}))|(GB(GD|HA)[0-9]{3})$');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='it'),'IT[0-9]{11}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='lt'),'(LT[0-9]{9})|(LT[0-9]{12})');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='lu'),'^LU[0-9]{8}$');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='lv'),'LV[0-9]{11}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='mc'),'FR[0-9A-Z]{2}[0-9]{9}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='mt'),'MT[0-9]{8}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='nl'),'NL[0-9]{9}B[0-9]{2}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='pl'),'PL[0-9]{10}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='pt'),'PT[0-9]{9}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='ro'),'RO[0-9]{2,10}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='se'),'SE[0-9]{12}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='si'),'SI[0-9]{8}');
insert into country_vat_config(id, country_id, vat_pattern) values (country_vat_config_id.nextval,(select id from country where lower(country_code)='sk'),'SK[0-9]{10}');

commit;

