package lu.luxtrust.flowers.integration.lrs.ws;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 3.2.1
 * 2018-02-24T14:19:35.016+02:00
 * Generated source version: 3.2.1
 * 
 */
@WebServiceClient(name = "LrsWSService", 
                  wsdlLocation = "http://backend.portal:12200/LrsWS/LrsWSService?wsdl",
                  targetNamespace = "http://ws.lrs.luxtrust.lu/") 
public class LrsWSService extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://ws.lrs.luxtrust.lu/", "LrsWSService");
    public final static QName LrsWSPort = new QName("http://ws.lrs.luxtrust.lu/", "LrsWSPort");
    static {
        URL url = null;
        try {
            url = new URL("http://backend.portal:12200/LrsWS/LrsWSService?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(LrsWSService.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://backend.portal:12200/LrsWS/LrsWSService?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public LrsWSService(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public LrsWSService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public LrsWSService() {
        super(WSDL_LOCATION, SERVICE);
    }
    
    public LrsWSService(WebServiceFeature ... features) {
        super(WSDL_LOCATION, SERVICE, features);
    }

    public LrsWSService(URL wsdlLocation, WebServiceFeature ... features) {
        super(wsdlLocation, SERVICE, features);
    }

    public LrsWSService(URL wsdlLocation, QName serviceName, WebServiceFeature ... features) {
        super(wsdlLocation, serviceName, features);
    }    




    /**
     *
     * @return
     *     returns LrsWS
     */
    @WebEndpoint(name = "LrsWSPort")
    public LrsWS getLrsWSPort() {
        return super.getPort(LrsWSPort, LrsWS.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns LrsWS
     */
    @WebEndpoint(name = "LrsWSPort")
    public LrsWS getLrsWSPort(WebServiceFeature... features) {
        return super.getPort(LrsWSPort, LrsWS.class, features);
    }

}
