package lu.luxtrust.flowers.enums;

public enum OrderStatus {
    DRAFT,
    USER_DRAFT,
    CSD_REVIEW_REQUIRED,
    DIA_SIGNING_REQUIRED,
    REMOTE_IDENTIFICATION_REQUIRED,
    FACE_2_FACE_REQUIRED,
    SENT_TO_LRS,
    PENDING_FINAL_IDENTIFICATION,
    PENDING_CSD_DECISION,
    REJECTED,
    LRS_ONGOING,
    LRS_PRODUCED,
    LRS_ACTIVATED,
    LRS_CANCELED
}
