package lu.luxtrust.flowers.enums;

public enum Permission {

    CREATE_CERTIFICATEORDER,
    EDIT_CERTIFICATEORDER,
    READ_CERTIFICATEORDER,
    CREATE_IN_BATCH_CERTIFICATEORDER,
    SIGN_AND_SEND_CERTIFICATEORDER,

    CREATE_UNIT,
    EDIT_UNIT,
    READ_UNIT,

    CREATE_USER,
    EDIT_USER,
    READ_USER,

    CREATE_ESEALORDER,
    EDIT_ESEALORDER,
    READ_ESEALORDER,
    ACTIVATE_ESEALORDER,
    SIGN_AND_SEND_ESEALORDER
}
